---
- ansible.builtin.include_tasks:
    file: pre.yml

- ansible.builtin.include_tasks:
    file: Remote Logging.yml

- name: Install rsyslog
  ansible.builtin.dnf:
    name:
      - rsyslog
    state: latest
  become: true
  notify: Enable & start rsyslog

- ansible.builtin.include_tasks:
    file: HAProxy.yml