---
- name: Enable & start rsyslog
  ansible.builtin.systemd_service:
    name: rsyslog
    state: started
    enabled: true
  become: true

- name: Restart rsyslog
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted
    daemon_reload: true
  become: true